FROM node:20.19.1-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=12345
ENV MONGO_URL=mongodb://DevopsDB:27017
ENV DB_NAME=DevopsDB
EXPOSE 12345

CMD ["npm", "start"]
